name:                taskflow-api
version:             0.1.0.0
github:              "githubuser/taskflow-api"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/taskflow-api#readme>

dependencies:
- base >= 4.7 && < 5
- containers >=0.6 && <0.7
- text
- bytestring
- time
- mtl
- template-haskell
- lens
- aeson
- servant
- servant-server
- warp
- persistent
- persistent-sqlite
- monad-logger
- esqueleto
- optparse-applicative
- http-client
- http-client-tls
- http-types
- stamina
- exceptions
- async
- stm
- network-uri
- scalpel-core
- relude
- QuickCheck
- hedgehog
- hedgehog-classes
- optics
- generic-optics
- rapid

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: [src, src/persistent]
  other-modules:
  - Schema

executables:
  taskflow-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taskflow-api

tests:
  taskflow-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taskflow-api
